BlogMainStructure.UI/Areas/Author/Controllers/TagController.cs
using BlogMainStructure.Business.DTOs.TagDTOs;
using BlogMainStructure.Business.Services.TagServices;
using BlogMainStructure.UI.Areas.Author.Models.TagVMs;
using Mapster;
using Microsoft.AspNetCore.Mvc;

namespace BlogMainStructure.UI.Areas.Author.Controllers
{
    public class TagController : AuthorBaseController
    {
        private readonly ITagService _tagService;

        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _tagService.GetAllAsync();
            if (!result.IsSuccess)
            {
                return View(result.Data.Adapt<List<AuthorTagListVM>>());
            }
            return View(result.Data.Adapt<List<AuthorTagListVM>>());
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorTagCreateVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await _tagService.AddAsync(model.Adapt<TagCreateDTO>());
            if (!result.IsSuccess)
            {
                return View(model);

            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _tagService.DeleteAsync(id);

            if (!result.IsSuccess)
            {
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");

        }
    }
}

BlogMainStructure.UI/Controllers/ArticleController.cs
using BlogMainStructure.Business.Services.ArticleServices;
using BlogMainStructure.UI.Extensions;
using BlogMainStructure.UI.Models.ArticleVMs;
using Mapster;
using Microsoft.AspNetCore.Mvc;

namespace BlogMainStructure.UI.Controllers
{
    public class ArticleController : BaseController
    {
        private readonly IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _articleService.GetAllAsync();
            var articleListVMs = result.Data.Adapt<List<ArticleListVM>>();

            foreach (var articleListVM in articleListVMs)
            {
                articleListVM.ReadingTime = await articleListVM.Content.CalcualteReadingTime();
            }

            if (!result.IsSuccess)
            {
                return View(articleListVMs);
            }
            return View(articleListVMs);
        }

        public async Task<IActionResult> IndexTop5()
        {
            var result = await _articleService.Top5GetAll();

            var articleListVMs = result.Data.Adapt<List<ArticleListVM>>();

            foreach (var articleListVM in articleListVMs)
            {
                articleListVM.ReadingTime = await articleListVM.Content.CalcualteReadingTime();
            }

            if (!result.IsSuccess)
            {
                return View(articleListVMs);
            }

            return View(articleListVMs);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _articleService.GetByIdAsync(id);

            if (!result.IsSuccess)
            {
                return RedirectToAction("Index");
            }

            return View(result.Data.Adapt<ArticleDetailVM>());
        }
    }
}

BlogMainStructure.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogMainStructure.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogMainStructure.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogMainStructure.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Author"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Author" asp-controller="Tag" asp-action="Index">Tags</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Author" asp-controller="Article" asp-action="Index">My Articles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="MyAccount">My Account</a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="IndexTop5">Top 5 Articles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogMainStructure.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>